version: '3.8'
services:
  odot:
    image: ghcr.io/zigsphere/odot-cameras:main
    #build: .
    restart: on-failure
    networks:
      - odot-net
    environment:
      - API_KEY=XXXXXXXXXXXXXXXX
      - REDIS_PASSWORD=password
    depends_on:
      - redis
  web:
    image: nginx
    restart: on-failure
    depends_on: 
      - odot
    networks:
      - odot-net
    ports:
      - 80:80/tcp
    volumes:
      - ./nginx-files/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-files/nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: bitnami/redis
    restart: on-failure
    networks:
      - odot-net
    environment:
      - REDIS_PASSWORD=password

networks:
  odot-net:
